[[docs]]
name = "起步"
weight = 10
identifier = "prologue"
url = "/docs/prologue/"

[[docs]]
name = "用户|获取/兑换/使用 皮肤"
weight = 20
identifier = "mark_use"
url = "/docs/mark_use/"

[[docs]]
name = "会员|使用 皮肤/打标 服务"
weight = 30
identifier = "mark_user"
url = "/docs/mark_user/"

[[docs]]
name = "额外功能|Logo/前景等"
weight = 30
identifier = "extra_service"
url = "/docs/extra_service/" 

[[docs]]
name = "公益功能|加密/转系统等"
weight = 30
identifier = "public_service"
url = "/docs/public_service/"

[[docs]]
name = "帮助"
weight = 60
identifier = "help"
url = "/docs/help/"

[[main]]
name = "关于我们"
url = "/docs/about/"
weight = 20
