# Meta Data for SEO

## Homepage
title = "JuneOver24 工具箱"
titleSeparator = "-"
titleAddition = "官方文档"
description = "JuneOver24 工具箱官方文档：皮肤、字体、音效与素材处理工具。"

## Open Graph
images = ["Logo.png"]
ogLocale = "zh_cn"
ogImageHeight = "320"
ogImageWidth = "640"
domainTLD = "docs.beautify.mp.juneover24.cn"
titleHome = "JuneOver24 工具箱官方文档"

## Twitter Cards
twitterSite = ""
twitterCreator = ""

## JSON-LD
schemaType = "Organization"
schemaName = "JuneOver24"
schemaAuthor = "JuneOver24"
schemaAuthorTwitter = ""
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/juneover24"
schemaLocale = "zh-CN"
schemaLogo = "android-chrome-512x512.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "Logo.png"
schemaImageWidth = 289
schemaImageHeight = 117
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/juneover24/beautify"
schemaSection = "docs"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Copyright (c) 2021 - {year} JuneOver24"
copyright = "Copyright (c) 2021 - {year} JuneOver24"

# Alert
alert = false
alertText = ""

# Edit Page
docsRepo = "https://github.com/juneover24/beautify"
editPage = true

# Contributors
githubContributors = false
githubUser = "juneover24"
githubRepo = "beautify"
githubDocRepo = "beautify"
githubDocTree = "main"
githubContributorsAPI = ""

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = true
  collapsibleSidebar = true
  docsNavigation = true
  lastModified = true

[dateFormat]
lastUpdated = "2006年01月02日 15:04:05 MST"
